def load(newPart,it):
    it['PROJ-SPAR-14877-STAN-01']['oompParts'] = [{'BT2': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'D1': 'LEDS-UNMATCHED-G-STAN-01', 'R1': 'RESE-UNMATCHED-X-O100-01', 'S2': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01'}]
