def load(newPart,it):
    it['PROJ-SPAR-9760-STAN-01']['oompParts'] = [{'S1': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'S2': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'S3': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'S4': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'S6': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'U1': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'U2': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01'}]
