def load(newPart,it):
    it['PROJ-PDP7-0006-STAN-01']['oompParts'] = [{'J1': {'OOMPID': 'HEAD-I01-X-UNMATCHED-01', 'FULL': {'DESC': '', 'PART': 'J1', 'DEVICE': 'TEENSY-LC TEENSY3.2-72MHz', 'PACKAGE': 'TEENSY-LC', 'PARTLETTER': 'J', 'VALUE': 'TEENSY3.2-72MHz', 'VALUENUMBER': '3.2-72', 'PACKAGENUMBER': '', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'J1,TEENSY3.2-72MHz,TEENSY-LC TEENSY3.2-72MHz,TEENSY-LC,,,'}},
       'J2': {'OOMPID': 'HEAD-I01-X-PI06-01', 'FULL': {'DESC': '', 'PART': 'J2', 'DEVICE': 'Pin_Header_Straight_1x06 OLED-I2C', 'PACKAGE': 'Pin_Header_Straight_1x06', 'PARTLETTER': 'J', 'VALUE': 'OLED-I2C', 'VALUENUMBER': '-2', 'PACKAGENUMBER': '106', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'J2,OLED-I2C,Pin_Header_Straight_1x06 OLED-I2C,Pin_Header_Straight_1x06,,,'}},
       'J3': {'OOMPID': 'HEAD-I01-X-PI07-01', 'FULL': {'DESC': '', 'PART': 'J3', 'DEVICE': 'Pin_Header_Straight_1x07 ADAFRUIT_BME280', 'PACKAGE': 'Pin_Header_Straight_1x07', 'PARTLETTER': 'J', 'VALUE': 'ADAFRUIT_BME280', 'VALUENUMBER': '_280', 'PACKAGENUMBER': '107', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'J3,ADAFRUIT_BME280,Pin_Header_Straight_1x07 ADAFRUIT_BME280,Pin_Header_Straight_1x07,,,'}},
       '3V3': {'OOMPID': 'HEAD-I01-X-PI01-01', 'FULL': {'DESC': '', 'PART': '3V3', 'DEVICE': 'Pin_Header_Straight_1x01 3V3', 'PACKAGE': 'Pin_Header_Straight_1x01', 'PARTLETTER': 'V', 'VALUE': '3V3', 'VALUENUMBER': '33', 'PACKAGENUMBER': '101', 'BOM': '', 'OWNER': 'PDP7', 'FULL': '3V3,3V3,Pin_Header_Straight_1x01 3V3,Pin_Header_Straight_1x01,,,'}},
       'GND1': {'OOMPID': 'HEAD-I01-X-PI01-01', 'FULL': {'DESC': '', 'PART': 'GND1', 'DEVICE': 'Pin_Header_Straight_1x01 GND', 'PACKAGE': 'Pin_Header_Straight_1x01', 'PARTLETTER': 'GND', 'VALUE': 'GND', 'VALUENUMBER': '', 'PACKAGENUMBER': '101', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'GND1,GND,Pin_Header_Straight_1x01 GND,Pin_Header_Straight_1x01,,,'}},
       'GPIO0': {'OOMPID': 'HEAD-I01-X-PI01-01', 'FULL': {'DESC': '', 'PART': 'GPIO0', 'DEVICE': 'Pin_Header_Straight_1x01 GPIO0', 'PACKAGE': 'Pin_Header_Straight_1x01', 'PARTLETTER': 'GPIO', 'VALUE': 'GPIO0', 'VALUENUMBER': '0', 'PACKAGENUMBER': '101', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'GPIO0,GPIO0,Pin_Header_Straight_1x01 GPIO0,Pin_Header_Straight_1x01,,,'}},
       'GPIO2': {'OOMPID': 'HEAD-I01-X-PI01-01', 'FULL': {'DESC': '', 'PART': 'GPIO2', 'DEVICE': 'Pin_Header_Straight_1x01 GPIO2', 'PACKAGE': 'Pin_Header_Straight_1x01', 'PARTLETTER': 'GPIO', 'VALUE': 'GPIO2', 'VALUENUMBER': '2', 'PACKAGENUMBER': '101', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'GPIO2,GPIO2,Pin_Header_Straight_1x01 GPIO2,Pin_Header_Straight_1x01,,,'}},
       'R1': {'OOMPID': 'RESE-UNMATCHED-X-UNMATCHED-01', 'FULL': {'DESC': '', 'PART': 'R1', 'DEVICE': 'Resistor_Horizontal_RM7mm R', 'PACKAGE': 'Resistor_Horizontal_RM7mm', 'PARTLETTER': 'R', 'VALUE': 'R', 'VALUENUMBER': '', 'PACKAGENUMBER': '7', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'R1,R,Resistor_Horizontal_RM7mm R,Resistor_Horizontal_RM7mm,,,'}},
       'RST1': {'OOMPID': 'HEAD-I01-X-PI01-01', 'FULL': {'DESC': '', 'PART': 'RST1', 'DEVICE': 'Pin_Header_Straight_1x01 RST', 'PACKAGE': 'Pin_Header_Straight_1x01', 'PARTLETTER': 'RST', 'VALUE': 'RST', 'VALUENUMBER': '', 'PACKAGENUMBER': '101', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'RST1,RST,Pin_Header_Straight_1x01 RST,Pin_Header_Straight_1x01,,,'}},
       'U1': {'OOMPID': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'FULL': {'DESC': '', 'PART': 'U1', 'DEVICE': 'ESP-01 ESP-01v090', 'PACKAGE': 'ESP-01', 'PARTLETTER': 'U', 'VALUE': 'ESP-01v090', 'VALUENUMBER': '-01090', 'PACKAGENUMBER': '01', 'BOM': '', 'OWNER': 'PDP7', 'FULL': 'U1,ESP-01v090,ESP-01 ESP-01v090,ESP-01,,,'}}}]
