def load(newPart,it):
    it['PROJ-ADAF-2566-STAN-01']['oompParts'] = [{'CN2': {'OOMPID': 'UNMATCHED-UNMATCHED-X-UNMATCHED-01', 'FULL': {'DESC': '', 'PART': 'CN2', 'DEVICE': 'JST_3PIN', 'PACKAGE': 'JSTPH3', 'PARTLETTER': 'CN', 'VALUE': '', 'VALUENUMBER': '', 'PACKAGENUMBER': '3', 'BOM': '', 'OWNER': 'ADAF', 'FULL': 'CN2,,JST_3PIN,JSTPH3,,,'}}}]
